name: Dart lint analysis and formatting

on:
  push:

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        working-directory: ./assistant-web-frontend

      - name: Install flutter
        uses: subosito/flutter-action@v2
        working-directory: ./assistant-web-frontend

      - name: Check format
        working-directory: ./assistant-web-frontend
        run: flutter format --line-length 120 --set-exit-if-changed ./assistant-web-frontend/lib

      - name: Analyze code
        working-directory: ./assistant-web-frontend
        run: flutter analyze